defaults: &defaults
 adapter: postgresql
 database: my_med_labs_call_center_development
 username: tammam
 password:
 encoding: unicode
 pool: 5

development:
 <<: *defaults

test:
 <<: *defaults
 database: my_med_labs_call_center_test

production:
 <<: *defaults